### ISSUE TITLE
Container is not starting

### ISSUE THREAD

**Issue by chavda-bhavik** [xpublisher/weasyprint-rest#75]
Thanks for this great Idea,

When I run following command,
```
docker run -p 5000:5000 -d xpublisher/weasyprint-rest:latest
```

Container is falling to start with following error,
![image](https://user-images.githubusercontent.com/50201755/188812029-8285f938-d38c-43c3-a284-0f3f01799f42.png)

Any Idea on possible fix? Thank you

**Comment by kpalatzky** [comment]
Hi @chavda-bhavik,

the service needs the /data/templates. You can just mount it in by creating a new empty directory i. e. "templates" and run:
`docker run -p 5000:5000 -v /path/to/local/templates:/data/templates -d xpublisher/weasyprint-rest:latest` 

(You have to replace the /path/to/local/templates with your real path).

Best
Kevin

**Comment by chavda-bhavik** [comment]
It worked, thank you so much @kpalatzky.

**Comment by chavda-bhavik** [comment]
@kpalatzky I believe if will be helpful to update start container command on Homepage to 
`docker run -p 5000:5000 -v /path/to/local/templates:/data/templates -d xpublisher/weasyprint-rest:latest`
on README.md file. What you think?

**Comment by kboshold** [comment]
@chavda-bhavik  i added it to the README.md.
